import './globals.css';
import '@cubik/presets/styles/style.css';
import '@cubik/presets/styles/lightColor.style.css';
import '@cubik/presets/styles/darkColors.styles.css';
import '@cubik/presets/styles/component.style.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Provider } from '@/app/provider';
import Header from '@/components/header';

import { cn } from '@cubik/ui/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="dark" lang="en">
      <body className={cn(inter.className, 'bg-white dark:bg-[var(--color-neutral-950)]')}>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
